### ISSUE TITLE
Mods that use letters in their patch version numbers are falsely placed in "updates" in the Dashboard

### ISSUE THREAD

**Issue by templeofshadow** [wispborne/TriOS#26]
Ok, so I've been having a very minor issue with the displaying of available updates. I've been ignoring it but I figured I'd still make an issue in order to make sure this isn't overlooked.

There are some mods that get put under the "updates" section of the mod sidebar in the dashboard, but are actually up to date. When I hover over the update button to see what TriOS thinks the current and new versions of the mod are, the "new" version of the mod is actually the version I already have, and the "current" version is some older version of the mod that I have in my mods folder. Crucially, this older version is a version that has a letter as a part of the "patch" portion of the version number. For example, with Nexerelin, it's picking up version 0.11.2 in my mods folder, which it correctly identifies as out of date, while not taking into account that I already have the most recent version also installed--0.11.2b--and deciding to put it into the "updates" section.

During my checking in order to make sure I wasn't going insane, when I went to the mods tab and checked the version drop-down for Nex, I noticed that 0.11.2b is not on the top of the list, it was 0.11.2.

So, with this, I had a suspicion. It was probably that TriOS doesn't properly sort version numbers if the patch number has a letter in it. 

After a frankly uncomfortable amount of looking around the TriOS code (I don't know Dart very well), I tracked the likely culprit down to the following line under Version.parse():
https://github.com/wispborne/TriOS/blob/ced5d9ead8af81fc92e6251d8b677e848586943e/lib/models/version.dart#L48

The regex `r"[^0-9.-]"` matches anything not 0-9, besides `.` or `-`, so this is likely where this issue is happening: During the process of sorting the modlist dropdown (specifically, calling ModVariant.bestVersion, which calls Version.parse()), TriOS removes any alphabetical characters and doesn't consider them when sorting, thus allowing for any mods with versions `[0-9]+\.[0-9]+\.[0-9]+[a-z]+` to be considered the same as `[0-9]+\.[0-9]+\.[0-9]+` when finding the highest version, which causes the behavior outlined above.

I hope my overly extensive analysis helped in some way if you weren't aware of honestly insignificant tiny bug already.

**Comment by wispborne** [comment]
This is the gold standard of bug reports. Thank you!

I'll fix it ASAP, but did have a chance to look into how this happened...every bug is a story :)

SMOL uses two different Version objects; one for the version in `mod_info.json`, and one for the one in the `.version` file.
The parsing logic you found is from SMOL's `mod_info.json` parser.

TriOS, by mistake/rushing, uses SMOL's `mod_info.json` Version object (and logic) for *both* things, and you can guess what the main difference is; the SMOL `.version` file logic, which is absent from TriOS, doesn't strip out the letters.


The reason that stripping out the letters makes sense in the first place is that the `mod_info.json` file's version field doesn't enforce any kind of format (e.g. major, minor, patch), making parsing out the major/minor/patch challenging. Removing all but numerics apparently helped with that. (Seriously, which is higher, "4g555566g.i" or "4ghg44444.x.4"? This is hyperbole but not by as much as I wish.)

The reason this isn't a *problem* in SMOL is that both programs will always favor sorting by the `.version` file's version, if it exists, rather than the mod info one, because the enforced major/minor/patch format makes it reliable.

Anyway the proper fix is to uncomment and use this: https://github.com/wispborne/TriOS/blob/ced5d9ead8af81fc92e6251d8b677e848586943e/lib/models/version_checker_info.dart#L25 
...or perhaps I can get away with simply adding a parameter to `Version`'s constructor to not "sanitize" the input when reading from the `.version` file.

**Comment by templeofshadow** [comment]
Thanks for that. I had nothing to do this morning and the bug just happened to catch my eye, so I figured I'd look into it.

Having to support both the mod_info.json ""standard"" and the .version standard seems like quite an annoyance for this project. I can definitely imagine that it would've been easier in development to just cut the letters in order to get the version number without the bs. Especially with stuff like SCAV-CO's version X-6 (not trying to throw shade, that's a sick version number, but it's also a pain to sort).

On that topic, I have seen some of the versioning that you're referring to, with the worst offender being Commissioned Crews (no offense to Techpriest, love the mod, but... seriously? 1.999999gggg? at that point just use like hexadecimal or something and go with 1.0xA lol), but on a more serious note, I can definitely see how that can be a difficult problem, what with everyone deciding on their own standards for versioning. I guess we're lucky most people stick to major.minor.patch standard, because it'd be extremely difficult to decide what to update otherwise. Dealing with all ascii characters as numerals for a base-128 number system... ugh. It annoys me just thinking about it (please, to any modders reading this for whatever reason, please don't do that).

As for those fixes, since I'm not particularly familiar with either Dart or the TriOS codebase so I won't really say anything besides I hope you don't find much trouble with it. It would seem that that VersionCheckerInfo class wouldn't need much modification to retrofit into the existing Version class, so I think I would look into that first if it were me (since I'm susceptible to the sunk cost fallacy lol), but either way, as long as it works, right?

Anyways, that's about all I have to say. Good luck and happy bug-squashing.

**Comment by wispborne** [comment]
After all that excitement, I haven't actually been able to reproduce this.

<img width="923" alt="image" src="https://github.com/wispborne/TriOS/assets/1343347/bbba53d4-50aa-4e39-9cc8-b139cfb9af9c">

<img width="541" alt="image" src="https://github.com/wispborne/TriOS/assets/1343347/5a57175d-9e68-403c-9bfb-f11d7a153cde">

<img width="134" alt="image" src="https://github.com/wispborne/TriOS/assets/1343347/3425ecca-30b3-40d7-9601-31571286d4b0">


This is on TriOS v0.0.52.

**Comment by wispborne** [comment]
The plot thickens?

I can reproduce it on v0.0.52 on **Windows**. The above screenshots were taken on MacOS.

No idea why there's a difference, but now I can test the fix!

**Comment by wispborne** [comment]
Fixed in v0.0.53, confirmed with both Nex and the Vass no longer having "updates" in the patched version.
However, it's not quite ready for release...the whole mod grid UI is being swapped for a different library that supports sections, column reordering, filtering rows, auto-resize, and a bunch more.

![image](https://github.com/wispborne/TriOS/assets/1343347/6119254a-39d7-4de8-a5db-e60979f96411)

**Comment by templeofshadow** [comment]
Firstly, as a response to comments 3 and 4, yeah that's really weird. I didn't think to mention my OS since the issue appeared to happen within the raw code. The only thing I can think of is maybe a difference in compiler config, or a compiler difference in general? As I said earlier, I don't know Dart very well so what I just said is from my C++ experience... Well, whatever. 

Anyways. After reading through the commit (specifically this: https://github.com/wispborne/TriOS/blob/32152ee0f39a6642d111d6e5d49eb6074d816cbe/lib/models/version.dart#L49-L51), seems good to me. At least, the specific bugged behavior I reported in this issue is fixed, and shouldn't happen most of the time unless the sort falls back onto mod_info.json, in which case it shouldn't matter since the mod wouldn't support version checker and thus wouldn't be able to update properly within TriOS in the first place. As such, I'll close this issue with this comment.

Thanks for making TriOS, endless respect.

**Comment by wispborne** [comment]
Here's a dev build with the fix. The biggest bug in it I've noticed so far is that scrolling gets reset whenever the mod grid updates...something weird with the new DataGrid component.

[Dev-53-TriOS.zip](https://github.com/user-attachments/files/15839247/Dev-53-TriOS.zip)

**Comment by templeofshadow** [comment]
Yeah, I just pulled it up and tried it, and it fixes this (#26) issue. 

There are some other bugs I noticed during my quick peruse, but it's mostly what you mentioned and the on-hover tooltip windows being a little weird. The windows on the dashboard aren't positioned properly for the first 13 mods when the application isn't maximized, but when the app is maximized, only those 13 tooltips are displayed (and in their correct positions), and all subsequent tooltips aren't displayed. The tooltips for the mods under "updates" have the same issue. Here's a screenshot for this:
![image](https://github.com/wispborne/TriOS/assets/66976515/94c153cd-91e4-4f04-9a0b-00e7922d14b5)
My mouse doesn't show up in the snip, but in that image I'm hovering over the 'n' in "Confidence" (this screenshot was taken after the tooltips in the mod manager got a little too clingy, see next paragraph).

Then, when reproducing what you mentioned with how the scrolling gets reset in the mods tab, I noticed that for some reason tooltips sometimes get frozen a few moments after the scroll position is reset. I didn't notice anything different between where this did and didn't happen, so nothing to say for reproducing this issue, but here's a screenshot: 
![image](https://github.com/wispborne/TriOS/assets/66976515/4b626cfd-ce1c-4e88-b176-17905d4ecf48)
I've experienced this before once or twice with earlier TriOS versions, but I had no way to reproduce it and it seemed random, so I never reported it since I had too little information. But, it seems much more common in this dev version, not to mention tentatively reproducible? IDK about all the other times it happened in earlier versions, but with this, it seems to happen pretty reliably if you have a tooltip window open a short time after having the scroll position reset. The timing at which this "freeze" occurs, however, seems random. 

Also, only one out of the two mod updates is displayed under "updates" in the dashboard. You can see this slightly in the first screenshot. The first is the one you can see, but Apex Design Collective also needs an update. This is reflected fine in the mod manager: 
![image](https://github.com/wispborne/TriOS/assets/66976515/d78e0ca8-1c22-43c9-9cf8-8914b0794832)
and the "updates" section in the dashboard reflects the amount of updates, but it only displays one update and not both:
![image](https://github.com/wispborne/TriOS/assets/66976515/3815603f-5ab4-4125-8b5f-80ab622f2b42)

I realize that this issue isn't really the best place to give feedback on this, but IDK where else I'd put this for a dev version, so since this is where you posted it here you go i guess. Oh yeah, and as for OS I'm running on Windows 10, and I don't have a particularly strange hardware config. 

Anyways, apart from those issues it appears to work just as well as my v0.0.52 install, with the added benefit of seeing all of my mod versions that I save for no good reason via resizing the versions column and having updates in the dashboard always be real instead of sometimes be imaginary ;). 

Thanks for the quick fix for this issue and keep up the good work.
