### ISSUE TITLE
Download progress windows do not vanish after time or switching tabs

### ISSUE THREAD

**Issue by SirHartley** [wispborne/TriOS#27]
Pressing the "Update All" button causes a bunch of stacked progress windows to appear, which never vanish, even if tabs are switched. Due to their position it becomes impossible to edit the mods section and they all have to be close manually, which is inconvenient.

![image](https://github.com/wispborne/TriOS/assets/71236056/d16b2a91-21d1-4406-a776-f2b121165198)

**Comment by wispborne** [comment]
Leaving this open until I add a Clear All button, but they do dismiss automatically now.
