### ISSUE TITLE
Updating mods through the "Update All" button provides too little feedback

### ISSUE THREAD

**Issue by SirHartley** [wispborne/TriOS#28]
Since I didn't even know if these mods are save compatible, I really wanted to check the changelogs first, but it seems like TriOS downloads and immediately enables these mod updates. As there is currently no way to check changelogs at a glance in TriOS a user may not know which mods they just downloaded and updated, necessitating a bunch of manual switching.

Having a checkbox asking for permission ("Enable all downloaded mods?") would fix this.

**Comment by wispborne** [comment]
Need to come up with a general fix for this.
SMOL handled it by having a notification for every news added/updated mod with an `Enable` button. It's a little clunky but it handles all(?) situations, letting the user decide for each mod.

**Comment by wispborne** [comment]
In 0.1.0, it will not automatically enable newly updated mods, and will display a notification with an Enable button.
