### ISSUE TITLE
Feature: Prompt to force-update game version when enabling outdated mods

### ISSUE THREAD

**Issue by Dessix** [wispborne/TriOS#59]
In my setup, about 15 mods ended up needing their `mod_info.json` updated to contain `gameVersion: "0.97a-R11"` while being listed as `0.96a*`-supporting. Manually doing this is a bit of a chore, and the game will automatically disable them on startup if they don't match.

It would be nice if the system would automatically patch in a faked current version when enabling mods that aren't currently supported in the target version of the game. It's probably important to keep a note that the mod may still be incompatible, and potentially warn the user or require confirmation when enabling an out-of-date mod.

**Comment by wispborne** [comment]
You can right-click a mod in TriOS and choose "Force to <currentVersion>" and it'll do that :)
It adds a line to the `mod_info.json` showing the original game version, as well.

There's no way to do it in batch in TriOS.

**Comment by wispborne** [comment]
When enabling an outdated mod, I could add a dialog asking if you want to "force-enable" it, with lots of warnings.

**Comment by Dessix** [comment]
That could be nice- I ended up manually updating all of my files because I simply didn't discover the force feature you described. Perhaps a little button next to the version number on outdated mods would be smooth enough?

**Comment by wispborne** [comment]
Added in 1.0
