### ISSUE TITLE
Feature: Enable allocation of 32GB RAM to Starsector

### ISSUE THREAD

**Issue by nissa-seru** [wispborne/TriOS#69]
Title - context is that I enjoy consistently having 140fps when running at 2x combat speed :P

**Comment by wispborne** [comment]
How much RAM is being used ,per Console Commands, with 16 GB allocated?

**Comment by nissa-seru** [comment]
Any chance you could point me towards the current version of Console Commands? I'd mentally written it off as outdated since the last release I'd seen on the repo (https://github.com/LazyWizard/console-commands) was in May 2023. Is there another version best to use or should I just grab that one and uprev the game version in mod_info if needed?

**Comment by wispborne** [comment]
It's the latter - the 0.96a one works fine.

**Comment by nissa-seru** [comment]
Looks like 2.2GB in use out of 16GB allocated, 7.1GB of free VRAM; I might
be CPU-bound then - thanks for the nudge.

**Comment by wispborne** [comment]
:D
Almost all the time, anything more than 8GB is a waste or even slows the game down, but it was still worth checking.

I changed that section a little bit already yesterday, before I saw your message.

![image](https://github.com/user-attachments/assets/355ff02b-1b03-40e3-8091-90717b5a1733)
