### ISSUE TITLE
Feature: Enable user to redownload the current version of a mod, even if it is up to date

### ISSUE THREAD

**Issue by nissa-seru** [wispborne/TriOS#76]
Use case: Easy first troubleshooting step if experiencing issues with a mod, especially if it was originally manually installed or there's reason to suspect that files may be missing/corrupted.

**Comment by wispborne** [comment]
![image](https://github.com/user-attachments/assets/7496bb5c-8cff-4afb-9efd-d8b423802bac)

**Comment by nissa-seru** [comment]
Minor but sharing here in case helpful as data point - it looks like at least one possible error that shows up when using this functionality is super verbose for the amount of time that it appears on screen, and I don't immediately see how to view it again without just pushing the "Redownload & Reinstall" button again. Not looking for resolution of my specific case but sharing the general sequence of events in case helpful re toast duration for dialogues containing error messages.

![Screenshot 2024-08-23 125537](https://github.com/user-attachments/assets/5e439214-a614-43cc-8595-a819d8a3c280)
