### ISSUE TITLE
Feature: "Date installed" column

### ISSUE THREAD

**Issue by nissa-seru** [wispborne/TriOS#77]
Use case: Helpful for tracking all sorts of things, but maybe especially helpful if experiencing a new issue to have an easy-to-check reference of which new mods the user installed.

Added value: "Date last enabled" column

**Comment by wispborne** [comment]
Good idea but right now I don't store any mod info except for a version checker cache, so this feature includes adding mod metadata storage.

**Comment by wispborne** [comment]
Do `dateFirstSeen` at both the mod and version scopes.

**Comment by wispborne** [comment]
Done for 1.0
