### ISSUE TITLE
Feature Request - a search function

### ISSUE THREAD

**Issue by Anexgohan** [wispborne/TriOS#8]
Just a simple request
Please if possible add a search function on the Dashboard, under the right panel "Mods". Something like fuzzy search where as I type the name of mod irrelevent names dissapear leaving only matching results.
I think this would be really helpful as more and more mods get added the list grows to be difficult to navigate and manage or quickly find installed mods.
Thanks.

**Comment by wispborne** [comment]
Done in 0.0.58
