### ISSUE TITLE
Unclear hover text for "Rename mod folders" in v0.2.0-dev01

### ISSUE THREAD

**Issue by nissa-seru** [wispborne/TriOS#87]
Current hover text for reference:
![Screenshot 2024-09-02 025102](https://github.com/user-attachments/assets/21c46f3e-8fa6-42a7-91c4-4f2665644d6d)

Recommend something like:

"If enabled, TriOS will change the name of the folder containing the current version of a mod to "{modName}". Names of folders containing previous versions will not be changed; they will remain named as "{modName}_{modVersion}"

If disabled, TriOS will not change the name of any folders; each version of a mod will remain named as "{modName}_{modVersion}""

Clarity has a subjective element of course! Just writing out a quick issue since I realized that I couldn't parse the hover text well enough to understand whether the feature was working as intended.

**Comment by wispborne** [comment]
If enabled, TriOS will always add the version number to the folder name when installing a mod.
For example; LazyLib-1.8b, LazyLib-1.8, LazyLib-1.7.

If disabled, the latest version of a mod won't have its folder name changed. Older versions still will. For example; LazyLib, LazyLib-1.8, LazyLib-1.7.

**Comment by wispborne** [comment]
![image](https://github.com/user-attachments/assets/375021b0-5de3-414d-8409-a1711a179803)

**Comment by wispborne** [comment]
Closing for my sanity (it's the last open item in 0.2.0), but let me know if it's still unclear. Had a lot of trouble explaining this one in a tooltip.
